/*
 * encoding:utf-8
 * 
 * Autores: María Sánchez Marcos y Darío Megías Guerrero
 */
package s4;

import java.awt.Color;

/**
 *
 * @author dario
 */
public class PanelBotones extends javax.swing.JPanel {

    /**
     * Creates new form PanelBotones
     */
    public PanelBotones() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        acelerar = new javax.swing.JToggleButton();
        frenar = new javax.swing.JToggleButton();
        encender = new javax.swing.JToggleButton();
        estado = new javax.swing.JLabel();

        acelerar.setText("ACELERAR");
        acelerar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acelerarActionPerformed(evt);
            }
        });

        frenar.setText("FRENAR");
        frenar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                frenarActionPerformed(evt);
            }
        });

        encender.setFont(new java.awt.Font("DejaVu Sans", 1, 12)); // NOI18N
        encender.setForeground(new java.awt.Color(0, 255, 0));
        encender.setText("ENCENDER");
        encender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                encenderActionPerformed(evt);
            }
        });

        estado.setFont(new java.awt.Font("DejaVu Sans", 1, 18)); // NOI18N
        estado.setForeground(new java.awt.Color(255, 0, 51));
        estado.setText("APAGADO");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(encender, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(acelerar, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(frenar, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(186, 186, 186)
                        .addComponent(estado)))
                .addContainerGap(10, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(estado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(encender, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(acelerar, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(frenar, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(16, 16, 16))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void encenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_encenderActionPerformed
        if (encender.isSelected()) {
            encender.setText("APAGAR");
            encender.setForeground(Color.red);
            estado.setText("ENCENDIDO");
        } else {
            estado.setText("APAGADO");
            encender.setText("ENCENDER");
            encender.setForeground(Color.green);
            acelerar.setSelected(false);
            frenar.setSelected(false);
        }
        
        repaint();
        revalidate();
    }//GEN-LAST:event_encenderActionPerformed

    private void acelerarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acelerarActionPerformed
        if (!frenar.isSelected()) {
            if (acelerar.isSelected()) {
                acelerar.setText("Soltar acelerador");
                acelerar.setForeground(Color.red);
            
            if (encender.isSelected())
                estado.setText("ACELERANDO");
            
            } else {
                acelerar.setText("ACELERAR");
                acelerar.setForeground(Color.black);
            }
            
            repaint();
            revalidate();
        }
    }//GEN-LAST:event_acelerarActionPerformed

    private void frenarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_frenarActionPerformed
        if (!acelerar.isSelected()) {
            if (frenar.isSelected()) {
                frenar.setText("Soltar freno");
                frenar.setForeground(Color.red);
            
            if (encender.isSelected())
                estado.setText("FRENANDO");
            
            } else {
                frenar.setText("FRENAR");
                frenar.setForeground(Color.black);
            }
            
            repaint();
            revalidate();
        }
    }//GEN-LAST:event_frenarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton acelerar;
    private javax.swing.JToggleButton encender;
    private javax.swing.JLabel estado;
    private javax.swing.JToggleButton frenar;
    // End of variables declaration//GEN-END:variables
}
